export const REQUEST_AIRPORTS = 'REQUEST_AIRPORTS';
export const RECEIVE_AIRPORTS = 'RECEIVE_AIRPORTS';
export const CHOOSE_AIRPORTS = 'CHOOSE_AIRPORTS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';